variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
    - node_modules/

stages:
  - test

test-backend:
  image: python:3.7-alpine
  stage: test
  script:
    - pip install tox
    - (cd backend; tox)

test-frontend:
  image: node
  stage: test
  script:
    - cd frontend
    - npm install
    - npm run lint