image: python:3.7.5

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: nice_marmot
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: "runner-password"

before_script:
  - pip install pipenv
  - pipenv lock --dev --requirements > requirements.txt
  - pip install -r requirements.txt
  - rm .env

codestyle:
  script:
    - python -m flake8 **/*.py

test:
  script:
    - python -m coverage run --source src -m pytest src/tests/*.py
    - python -m coverage html
    - python -m coverage report -m 
  artifacts:
    when: always
    paths:
      - htmlcov
    expire_in: 1 day
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
