stages:
  - test

test-backend:
  image: python:3.8-alpine
  stage: test
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - backend/.cache/pip
  script:
    - pip install tox
    - cd backend
    - tox

test-frontend:
  image: node:current-alpine
  stage: test
  cache:
    paths:
      - frontend/node_modules
      - frontend/src/node_modules
      - frontend/.yarn
  script:
    - yarn
    - yarn lint

