image: python:3.7.5

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install pipenv
  - pipenv install
  - pipenv install pyfakefs

test:
  script:
    - ./tests
