image: python:3.7-alpine

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


services:
  - postgres:12.2-alpine


variables:
  POSTGRES_DB: nice_marmot
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: "runner-password"

stages:
  - test

lint:
  stage: test
  script:
    - pip install flake8
    - python -m flake8

test:
  stage: test
  script:
    - apk add build-base libffi-dev
    - pip install pipenv
    - pipenv lock --requirements > requirements.txt
    - echo pytest >> requirements.txt
    - echo pytest-asyncio >> requirements.txt
    - echo pyfakefs >> requirements.txt
    - echo coverage >> requirements.txt
    - pip install -r requirements.txt
    - python -m coverage run --source src -m --omit="src/tests/**/*.py" pytest
    - python -m coverage html 
    - python -m coverage report --skip-covered -m 
  artifacts:
    when: always
    paths:
      - htmlcov
    expire_in: 1 day
  coverage: '/^TOTAL.*\s+(\d+\%)$/'