image: python:3.7-alpine

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


services:
  - postgres:12.2-alpine


variables:
  POSTGRES_HOST: postgres
  POSTGRES_DB: toucandb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"

stages:
  - test

test:
  stage: test
  script:
    - apk add build-base libffi-dev
    - pip install tox
    - (cd backend; tox)
    - (cd backend/dataclass; tox)
    - (cd backend/database; tox)
    - (cd backend/storage; tox)
    - (cd backend/runner; tox)
    - (cd backend/coreservices; tox)