---
- hosts: all
  tasks:
    - name: Install packages
      become: true
      pacman:
        name:
          - docker
          - docker-compose
          - pyenv
          - base-devel
          - zsh
          - git
          - postgresql
        state: present
    - name: Enable docker service
      become: true
      service:
        name: docker
        state: started
        enabled: yes
    - name: Add user to docker group and set default shell
      become: true
      user:
        name: vagrant
        group: docker
        shell: /usr/bin/zsh
    - name: Install python 3.7.5 using pyenv
      command: pyenv install 3.7.5
      args:
        creates: /home/vagrant/.pyenv/versions/3.7.5
    - name: Install zsh antigen
      get_url:
        url: https://git.io/antigen
        dest: /home/vagrant/antigen.zsh
    - name: Install awscli
      command: /home/vagrant/.pyenv/versions/3.7.5/bin/pip install awscli
