version: '3'
services:
  database:
    image: "postgres:12"
    env_file:
      - devenv/database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4599:4567-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs,s3
    volumes:
      - localstack-tmp:/tmp/localstack
volumes:
  database-data:
  localstack-tmp: